name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Sync application files (with protection for user uploads)
      uses: easingthemes/ssh-deploy@v5.0.0
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        SOURCE: "./"
        TARGET: "public_html/hana.laratest.my.id"
        # DITAMBAHKAN: Melindungi folder tempat file unggahan disimpan
        EXCLUDE: "/.git/, /node_modules/, /vendor/, /storage/app/public/"

    - name: Run setup commands on server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          cd public_html/hana.laratest.my.id
          echo "🚀🚀🚀 Mulai Proses Deploy Laravel 🚀🚀🚀"

          # 1. Setup .env file
          cp .env.example .env
          echo "🚀🚀🚀 Laravel .env Berhasil Disalin 🚀🚀🚀"
          sed -i "s|APP_URL=http://localhost|APP_URL=http://hana.laratest.my.id/|g" .env
          echo "🚀🚀🚀 Laravel .env Berhasil Disalin 🚀🚀🚀"
          sed -i "s|DB_DATABASE=laravel|DB_DATABASE=koda1984_sistem-hana|g" .env
          echo "🚀🚀🚀 Laravel DB_DATABASE Berhasil Disalin 🚀🚀🚀"
          sed -i "s|DB_USERNAME=root|DB_USERNAME=koda1984_10sarea-admin|g" .env
          echo "🚀🚀🚀 Laravel DB_USERNAME Berhasil Disalin 🚀🚀🚀"
          sed -i "s|DB_PASSWORD=|DB_PASSWORD=bangkinang123|g" .env
          echo "🚀🚀🚀 Laravel DB_PASSWORD Berhasil Disalin 🚀🚀🚀"
          sed -i "s|APP_NAME=laravel|APP_NAME=UMKM Hana|g" .env

          # 2. Run Laravel installation and optimization
          composer install --optimize-autoloader
          echo "🚀🚀🚀 Laravel Install Dan Update Berhasil 🚀🚀🚀"
          php artisan key:generate
          echo "🚀🚀🚀 Laravel Key Generate Berhasil 🚀🚀🚀"
          php artisan optimize:clear
          echo "🚀🚀🚀 Laravel Optimize Clear Berhasil 🚀🚀🚀"
          php artisan migrate:fresh --seed
          echo "🚀🚀🚀 Laravel Migrate Fresh Seed Berhasil 🚀🚀🚀"
          php artisan key:generate
          echo "🚀🚀🚀 Laravel Key Generate Berhasil 🚀🚀🚀"
          # composer update
          composer dump-autoload
          echo "🚀🚀🚀 Laravel Composer Dump Autoload Berhasil 🚀🚀🚀"

          # 3. Create storage link manually
          if [ -L "public/storage" ]; then
              rm "public/storage"
          fi
          ln -s $PWD/storage/app/public $PWD/public/storage
          echo "🚀🚀🚀 Laravel Storage Link Berhasil 🚀🚀🚀"

          echo "🚀🚀🚀Semua Step Berhasil Dijalankan 🚀🚀🚀"